# docs: https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions

name: Verilator

on:
  push:
    branches: ["main", "dev-goog", "dev-msft", "wkuna/62360-deployable-cov-report"]
  workflow_call:
  workflow_dispatch:

env:
  CARGO_INCREMENTAL: 0
  SCCACHE_VERSION: 0.3.3
  RISCV_VERSION: v12.1.0
  VERILATOR_VERSION: v5.012
  PKG_CONFIG_PATH: /opt/verilator/share/pkgconfig
  SCCACHE_GHA_CACHE_TO: sccache-verilator-10000
  SCCACHE_GHA_CACHE_FROM: sccache-verilator-
  # Change this to a new random value if you suspect the cache is corrupted
  SCCACHE_C_CUSTOM_CACHE_BUSTER: f3e6951f0c1e

jobs:
  build_tools:
    name: Build Tools
    runs-on: ubuntu-22.04

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Restore Cargo index
        uses: actions/cache/restore@v3
        id: cargo_index_restore
        with:
          path: ~/.cargo/registry/index
          key: cargo-index-${{ env.SCCACHE_C_CUSTOM_CACHE_BUSTER }}-${{ hashFiles('Cargo.lock') }}

      - name: Restore sccache binary
        uses: actions/cache/restore@v3
        id: sccache_bin_restore
        with:
          path: ~/.cargo/bin/sccache
          key: sccache-bin-${{ env.SCCACHE_VERSION }}-${{ env.SCCACHE_C_CUSTOM_CACHE_BUSTER }}

      - name: Install sccache
        if: steps.sccache_bin_restore.outputs.cache-hit != 'true'
        run: |
          cargo install sccache --version ${SCCACHE_VERSION} --no-default-features --features=gha
      - name: Save sccache binary
        uses: actions/cache/save@v3
        if: steps.sccache_bin_restore.outputs.cache-hit != 'true'
        with:
          path: ~/.cargo/bin/sccache
          key: sccache-bin-${{ env.SCCACHE_VERSION }}-${{ env.SCCACHE_C_CUSTOM_CACHE_BUSTER }}

      - name: Configure sccache
        uses: actions/github-script@v6
        with:
          script: |
            core.exportVariable('ACTIONS_CACHE_URL', process.env.ACTIONS_CACHE_URL || '');
            core.exportVariable('ACTIONS_RUNTIME_TOKEN', process.env.ACTIONS_RUNTIME_TOKEN || '');
      - name: Restore verilator dir
        uses: actions/cache/restore@v3
        id: verilator_restore
        with:
          path: /opt/verilator
          key: verilator-${{ env.VERILATOR_VERSION }}-${{ env.SCCACHE_C_CUSTOM_CACHE_BUSTER }}

      - name: Install verilator
        if: steps.verilator_restore.outputs.cache-hit != 'true'
        run: |
          sudo apt-get install flex bison libfl2 libfl-dev help2man
          cd /tmp/
          git clone -b "${VERILATOR_VERSION}" https://github.com/verilator/verilator
          cd verilator
          autoconf
          ./configure --prefix=/opt/verilator CXX="sccache g++"
          make -j6
          sudo make install
      - name: Save verilator dir
        uses: actions/cache/save@v3
        if: steps.verilator_restore.outputs.cache-hit != 'true'
        with:
          path: /opt/verilator
          key: verilator-${{ env.VERILATOR_VERSION }}-${{ env.SCCACHE_C_CUSTOM_CACHE_BUSTER }}

      - name: Setup verilator path
        run: |
          echo /opt/verilator/bin >> $GITHUB_PATH

      - name: Restore Risc V Toolchain
        uses: actions/cache/restore@v3
        id: riscv_restore
        with:
          path: /opt/riscv
          key: riscv-${{ env.RISCV_VERSION }}-${{ env.SCCACHE_C_CUSTOM_CACHE_BUSTER }}

      - name: Install Risc V Toolchain
        if: steps.riscv_restore.outputs.cache-hit != 'true'
        run: |
          # Building from source takes around 6.65 GB of disk and download size
          wget -O toolchain.tar.gz https://github.com/chipsalliance/caliptra-tools/releases/download/gcc-v12.1.0/riscv64-unknown-elf.gcc-12.1.0.tar.gz
          tar -xzf toolchain.tar.gz -C /opt/

      - name: Save riscv dir
        uses: actions/cache/save@v3
        if: steps.riscv_restore.outputs.cache-hit != 'true'
        with:
          path: /opt/riscv
          key: riscv-${{ env.RISCV_VERSION }}-${{ env.SCCACHE_C_CUSTOM_CACHE_BUSTER }}

      - name: Setup riscv path
        run: |
          echo /opt/riscv/bin >> $GITHUB_PATH

  build_matrix:
    name: Build Smoke Test matrix
    runs-on: ubuntu-22.04
    needs: build_tools
    outputs:
      test_names: ${{ steps.output-matrix.outputs.test_names  }}
    env:
      # Essentially, execute 'smoke_test_uart' only
      EXCLUDE_TESTS: "smoke_test_veer, smoke_test_mbox, smoke_test_mbox_cg, smoke_test_sha512, smoke_test_sha256, smoke_test_sha256_wntz, smoke_test_sha256_wntz_rand, smoke_test_sha_accel, memCpy_ROM_to_dccm, memCpy_dccm_to_iccm, hello_world_iccm, iccm_lock, c_intr_handler, smoke_test_ecc, smoke_test_hmac, smoke_test_kv, smoke_test_sram_ecc, smoke_test_ras, smoke_test_trng, smoke_test_qspi, smoke_test_uart, smoke_test_hw_config, smoke_test_kv_uds_reset, smoke_test_kv_securitystate, smoke_test_kv_ecc_flow, smoke_test_kv_hmac_flow, smoke_test_kv_hmac_multiblock_flow, smoke_test_kv_crypto_flow, smoke_test_kv_cg, pv_hash_and_sign, smoke_test_pcr_signing, smoke_test_fw_kv_backtoback_hmac, smoke_test_ecc_errortrigger, smoke_test_pcr_zeroize, smoke_test_ahb_mux, smoke_test_doe_rand, smoke_test_doe_scan, smoke_test_zeroize_crypto, smoke_test_doe_cg, smoke_test_datavault_basic, smoke_test_datavault_reset, smoke_test_datavault_lock, smoke_test_wdt, smoke_test_wdt_rst, smoke_test_cg_wdt, smoke_test_clk_gating, smoke_test_iccm_reset"
    steps:
      - uses: actions/checkout@v3
      - name: Install deps
        run: |
          sudo apt-get update -qy && sudo apt-get install -qy --no-install-recommends \
            python3-minimal python3-yaml
      - name: Build matrix
        id: output-matrix
        run: |
          echo "test_names=$(python3 .github/scripts/build_tests_matrix.py)" >> $GITHUB_OUTPUT

  build_and_test:
    name: Verilator
    runs-on: ubuntu-22.04
    needs: build_matrix

    strategy:
      fail-fast: false
      matrix:
        test_name: ${{fromJSON(needs.build_matrix.outputs.test_names)}}
        coverage: ["branch", "toggle"]

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: 'true'

      - name: Restore Cargo index
        uses: actions/cache/restore@v3
        id: cargo_index_restore
        with:
          path: ~/.cargo/registry/index
          key: cargo-index-${{ env.SCCACHE_C_CUSTOM_CACHE_BUSTER }}-${{ hashFiles('Cargo.lock') }}

      - name: Restore sccache binary
        uses: actions/cache/restore@v3
        id: sccache_bin_restore
        with:
          path: ~/.cargo/bin/sccache
          key: sccache-bin-${{ env.SCCACHE_VERSION }}-${{ env.SCCACHE_C_CUSTOM_CACHE_BUSTER }}

      - name: Restore verilator dir
        uses: actions/cache/restore@v3
        id: verilator_restore
        with:
          path: /opt/verilator
          key: verilator-${{ env.VERILATOR_VERSION }}-${{ env.SCCACHE_C_CUSTOM_CACHE_BUSTER }}

      - name: Restore Risc V Toolchain
        uses: actions/cache/restore@v3
        id: riscv_restore
        with:
          path: /opt/riscv
          key: riscv-${{ env.RISCV_VERSION }}-${{ env.SCCACHE_C_CUSTOM_CACHE_BUSTER }}

      - name: Setup verilator path
        run: |
          echo /opt/verilator/bin >> $GITHUB_PATH

      - name: Setup riscv path
        run: |
          echo /opt/riscv/bin >> $GITHUB_PATH

      - name: Run Caliptra Verilator Smoke Test
        run: |
          CALIPTRA_ROOT=$(pwd)
          mkdir -p $CALIPTRA_ROOT/results
          cd tools/scripts
          make verilator CALIPTRA_ROOT=$CALIPTRA_ROOT TESTNAME=${{ matrix.test_name  }} COVERAGE=${{ matrix.coverage }}| tee output.log

      - name: Verify Smoke Test Result
        run: |
           # Search the last 30 lines of the output for "TESTCASE PASSED"
           tail -n 30 output.log | grep "TESTCASE PASSED"
           # grep will return 0 if the search term is found, and 1 otherwise
           # A non-zero value will cause the github action to fail.
           ret=$?
           if [ ret -ne 0 ]
           then
             exit ret
           fi

      - name: Prepare coverage data
        run: |
          bash $CALIPTRA_ROOT/.github/scripts/convert_coverage_data.sh coverage.dat
          echo "convert_coverage_data.sh exited with RET_CODE = "$?
          mv coverage.info $CALIPTRA_ROOT/results/coverage_${{ matrix.test_name }}_${{ matrix.coverage }}.info
          cd ../..

      - name: Upload coverage artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: build_test_verilator_coverage_data
          path: ./results/*.info

  verify_test_results:
    name: Verify Verilator Test Results
    runs-on: ubuntu-22.04
    needs: build_and_test
    # Force to run even if the build_and_test job is skipped for some reason
    if: ${{ !cancelled() }}
    steps:
      - name: Print Verilator Aggregated Result
        run: |
          echo "build_and_test has a result of [${{ needs.build_and_test.result }}]"
          if [[ "${{ needs.build_and_test.result }}" != "success" ]]; then
            exit 1
          fi

  report_coverage:
    name: Report Verilator Test Coverage
    runs-on: ubuntu-22.04
    needs: build_and_test
    steps:
      - name: Download Coverage Reports
        uses: actions/download-artifact@v3
        with:
          name: build_test_verilator_coverage_data
          path: ./

      - name: Generate Reports
        run: |
          bash .github/scripts/gen_coverage_reports.sh

      - name: Pack artifacts
        uses: actions/upload-artifact@v3
        with:
          name: coverage_dashboard
          path: ./report


  generate_webpage:
    name: Generate Caliptra RTL webpage
    runs-on: ubuntu-22.04
    needs: build_and_test
    steps:
      - name: Download Coverage Reports
        uses: actions/download-artifact@v3
        with:
          name: build_test_verilator_coverage_data
          path: ./

      - name: Generate Coverage Dashboard
        if: github.ref_name == 'main'
        run: |
          # TODO: Once deploy URL for the page is known, change '../..' to URL of main index.html page
          LOGO_SRC=../../../_static/white.svg LOGO_HREF=../../../index.html bash .github/scripts/gen_coverage_reports.sh

      - name: Generate Coverage Dashboard Dev
        if: github.ref_name != 'main'
        run: |
          # TODO: Once deploy URL for the page is known, change '../..' to URL of main index.html page
          LOGO_SRC=../../../../_static/white.svg LOGO_HREF=../../../../index.html bash .github/scripts/gen_coverage_reports.sh

      - name: Rename Coverage Dashboard
        run: |
          mv report coverage_dashboard

      - name: Update webpage
        if: github.event_name != 'pull_request'
        run: |
          .github/scripts/update_webpage.sh ${{ github.ref_name }} ${{ github.event_name }} 0

      - name: Update webpage PR
        if: github.event_name == 'pull_request'
        run: |
          .github/scripts/update_webpage.sh ${{ github.ref_name }} ${{ github.event_name }} ${{ github.event.number }}

      - name: Pack artifacts
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: webpage
          path: ./public.new
