name: L0 smoke test regression suite

on:
  push:
  pull_request:

jobs:

  Test:
    runs-on: ubuntu-latest

    steps:
      - name: Install utils
        run: |
          sudo apt -qqy update && sudo apt -qqy --no-install-recommends install \
            git autoconf automake autotools-dev curl python3 python3-pip \
            libmpc-dev libmpfr-dev libgmp-dev gawk build-essential bison flex \
            texinfo gperf libtool patchutils bc zlib1g zlib1g-dev libexpat-dev \
            ninja-build ccache libfl2 libfl-dev gcc-riscv64-unknown-elf
          pip install pyyaml

      - name: Build Verilator
        run: |
          git clone https://github.com/verilator/verilator
          pushd verilator
            git checkout v5.002
            autoconf
            ./configure --prefix=/opt/verilator
            make -j `nproc`
            make install
          popd
 
      - name: Setup repository
        uses: actions/checkout@v2
        with:
          submodules: recursive
          path: Caliptra

      - name: Run L0 smoke test regression suite
        run: |
          export PATH=/opt/verilator/bin:$PATH
          export WORKSPACE=$GITHUB_WORKSPACE
          python3 Caliptra/tools/scripts/run_verilator_l0_regression.py
